---
development:
  cloud_name: breaknenter
  api_key: '357751277159634'
  api_secret: Mg0ChDe54a7C2wt3RFnalJi-7K0
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: breaknenter
  api_key: '357751277159634'
  api_secret: Mg0ChDe54a7C2wt3RFnalJi-7K0
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: breaknenter
  api_key: '357751277159634'
  api_secret: Mg0ChDe54a7C2wt3RFnalJi-7K0
  enhance_image_tag: true
  static_file_support: false
